---
# tasks file for mapr_hbasemaster

- name: install mapr-hbase-master
  become: yes
  become_user: root
  yum: name=mapr-hbase-master-{{hbase_version}}.{{hbase_build}} state=present
  when: inventory_hostname in groups["hbasemaster"]
